L = %s"቙𐀨"   <🆭𞸹>       b832 = 7 *  ( %d3   *  [ 4  <𝌀>     ]    98  ( 0 * 7  <>   <ௗ>   1963  %s"￨"   7  <𑄶>     )    ( 73  rl-     )    *  %d0.4   ""    / 994  %x8   o    / 85  [ 501  %b00-1   %xe3     ]      )    8  <>   *  %s"﹬"       