t = 21  ( <🤐>     )        pl- = / <𐎟𞺊>       Z-- = ( * 0  <>   49151043  <>     )        i = / [ 13  [ 7 *  %s"𐍐ව"   9 * 46  %s"഍"    / 1 * 459  <>     ]    [ Rg3    / 4  F     ]      ]    965  ( 3  ( ""   <>    / 0  ( <𗀀⑋>   0  <>     )    %xD.3    / %i""   1  ( ( L    / 9  [ 08  <𐡖>   * 1  ( 69  %b1-01010     )    4614664347 *  <>     ]     / %b1-1000     )      )    1  <꥟>   %s""   w    / 23235 *  [ [ *  <>    / R-     ]     / 1  <>   ( 98  <𞀢>     )    ( 95  x     )    8  %b1-0   <>     ]      )    %b11    / 9  x-2J-     )        