I = / [ 0  %b0.1.0001.11.0.111.1011111.00    / %b0   1077  ( * 1  [ 52  %d211.9.5109097.2957    / [ 15  ""     ]    4  %b00   k   *  %s""     ]    *  ( *  <𐔀>    / 2  <>   ""    / 4 * 4  "꯮𝔖𞸤"     )    0945624  ( [ <>     ]      )    99 * 931  ( 2  %x8    / 85  ( ( %x0   * 0  %i""     )      )    %d71-01    / <>     )    %s"୞"   ( %d92.6     )      )      ]        B = <>   11 *  [ * 3  <ഽ>   3  ( <⮽𐠆₏ͺ𞹓>     )     / %b1   5  f    / ( P1   5  "ᝮ␧𑄶"   *  %b0   * 787  %b01000    / 14  [ * 768  ""    / 295  %xEdD58.FCd.FD.Fa     ]    299  %x67   *  [ %d2-38     ]    9 * 995991  <݋>     )      ]     / W       