M = 5 * 12  [ [ 6  <>   <>   66  %x7-D   6  ( %d043     )     / %i""    / %s""    / 7 * 256  [ ""     ]    3  "🃀"     ]    330  k    / 6  [ *  %b0    / 49653 * 87677  %i"𐠶𞀈ᚁ"   395  %d8-1   8  ( 7  %b10.1   3  G     )      ]      ]    <࡟ᏸ>       u = k   [ %b1     ]        