R = / <>   [ m0-   71  ( <>     )    ( [ 8  A   * 164  [ * 22  ( [ 79  B     ]     / * 3  Z-2     )    7  W     ]      ]      )    ( * 993  ( Ma   <>    / 0 * 0  [ <ವ>   V    / %x4     ]    "꫷￈𞀦"    / 19 *  Z0    / %d98.8.97.2.5.6.9.36.43   8  %b01     )    208 *  <>   <>   * 2023401  <࡜𖿡𞥠>   01467  f   * 2  [ [ ( [ 9  q-    / <>   <𑇵഻𐘀>   %d2-0   * 6658  %xb   *  <>   *  ( [ J     ]     / <>   6 * 8  ""   86  <𐠹𑲷>     )    %i"ດ𑃩"    / 4  ( 4 * 9  ( [ 0  %b10-110     ]     / <>   y     )      )    %b0-0   P9     ]     / * 2  %s"꠺અ𐹿ក𐨕"    / %i"߀"     )      ]     / ""     ]      )      ]        