m = ( 1 * 0  g     )        K9 = / ( %b1   w     )    * 598  "᩠"   *  ""    / 68  <🥌𞸠🄍>   * 2  [ 866 *  %xE4a   2038  "ೆ"     ]    0  [ %b001010.01.011   [ ( 241  %xAF4A.de.5Ad   4  <>     )     / 57 * 21  [ <⿰𖩪>     ]      ]      ]    * 0  <𑌲𑑚𐣳Ⱡ⯒>       