G = / [ %b11-0   40  ( 519 *  %x6D7.8bf.f.Eb    / * 5  [ %xD-F    / <൉>    / 3  [ GDN     ]    [ 08  %b100   * 9  cO6i     ]     / %i"𐓔"     ]    00820334710  <𑈿ᢰ኶𞥠෵>     )     / * 9  %x6B-F     ]        