r = / ( 4  <𐠷𑑜𑵧>    / %b0-01     )    <>   [ 51  ""   ( ""   s4M   9 * 3  <Ꟃ𑅐>     )     / <>    / ""     ]    77  ""    / * 43  ""   *  %xc    / 09  "প"   33  %b1-1    / 5  ( %xB3   * 71  ""   "⹐﬽🅭"   ( [ *  l     ]    "𞄭᩠"    / *  %d11-2954     )     / b   066 * 6  <𐮙>    / x   81  [ 8 * 4  %s"඗"   <>    / [ %i"኉"     ]      ]      )        