f-4 = / [ 6 *  q    / [ [ 2 * 8  %s"ව"    / J   6 *  <𑛊>     ]    G   12  i7    / 6 * 5  %s"๜"   * 3  [ [ ( * 7244  ( 528 *  ( ( * 05  [ ( 071 *  %s""   %b1-0     )      ]      )     / *  ( 7  %d1.792.0   %d59   845  <>    / u     )     / * 89  %i"ⵯ"    / %b1-1   f   371346  %x2.CDd.e3   * 6  %s"ⱟ᧐"   <꧞>    / a   J-   %b10     )      )    %s"ꦀ𛀀"    / ( 6  %d8     )    *  r7   %s"ￚ𐏄🟠"    / %xF   * 8  [ 70  ( 83  %xC   <>   9  %xC-CEC   5 *  ""     )    <>   70 * 9  <>   %d3     ]    5 *  [ *  [ 5  %xE-F     ]    2 * 6  %s""   2  %b10     ]      )    ""   [ 97  [ %d2   %d9    / 15 *  [ d   %xDe8   <౛>   9  <>     ]    ( <ⴧ>   *  %x83   Y9    / 6 * 5  [ [ 3 *  eN     ]      ]     / * 4  %s""     )    %s"ೠ"   47  <>   6 * 35  %xA-e9E0    / <>   * 3  b7     ]     / [ ""   114244 *  ( ( <𞸥>     )    0664 *  <>     )     / %d0     ]      ]     / *  <>     ]      ]     / 9  ( 06  "ౘ𞹸"   903 *  %s"﹬"     )    "𑇡"     ]      ]        