L8Qi- = [ * 6  <>   *  %xdaadfe.F   * 1  <𝕇𑛀>   %xE.B   <>    / 201  %d1   %x2-9   82  ( <𖼀𐤟শ>   6557621  %s"਑⮖"     )    ( 4  ( C-   *  %d5-6   * 493  <꣆֍ቊܐ>   * 97  f-    / *  w-    / %b01.00   <᭽>   4 *  ( 9  <>    / *  ""   699  %b01    / i     )      )    <>     )    A    / 6  %d28405.5   <𞹾>     ]        M = 26 *  ( *  %s"꤀"    / [ "೟Ꭰⴧ"     ]    *  ( pwp    / 532 *  <>   FL     )      )        