f = / *  <ꧏ὘𑇎ຊ>   28  %xF   * 253  ( [ 0  <᠚㆐𞹐෇Ἐ>   89  <ⷠ>   * 2  M----   34628  [ %b111-1   82 *  %d746193-9     ]      ]    %d006-1   *  %d9.72.28.34966223    / <>   8  G55     )    9 * 78  <>   %x7.Da.C    / 24 *  %d552    / %b0011-1   *  X    / 1  <>   p-   L-       