c = / 332  vj   [ 4373  <𐀍቙ᴀ೦඗൅>   u1-     ]        l = / ( 444343  ( 27 * 0  ( 95 *  %b1-0    / V   %d4.24466     )    * 6  "𪜀"    / %b01   *  ""    / <ఽ>   <𘫳>     )      )    [ *  %b00111.00     ]     / 18  %s"𝒠𑝀"   7 *  %i""   15  [ 3  %d9     ]    %x923.B6e0c    / i-3Y    / <>    / 1  ( B    / 79 * 78547  ( m   [ 2  ( *  %b111     )    <𑃂>     ]      )    2 * 3  <>    / <>   <ਓ>    / [ <𐇾Ʞᭌ>   <>   "𑈿઱"     ]      )     / n       D--- = %i"ퟋ﹨"       