e2 = ( 5 *  <፝>    / ""     )    <🡠>   5  ( *  %b0   58  %x49-b   * 6541  [ * 4860  GV-3     ]      )    *  [ 2  [ %b001.1.11    / 0187 *  b-M     ]    *  ""   %xbDEC   *  t1     ]        Z-7 = 7 * 9  <ⷀ>   <Ⴧ>    / * 7  Xv   1  n   2  <຺>    / * 4  <⯉⶯𐕤Ό>       